# action.yml
name: 'Export Namespace'
description: 'Export a namespace.'
inputs: 
  openshift-namespace:  
    description: 'Namespace'
    required: true 
runs:
  using: "composite"
  steps: 
    - run: "curl https://raw.githubusercontent.com/jduimovich/gitops-export/main/scripts/boot.sh | bash"
      shell: bash 
