#!/bin/bash 
OUTPUT_DIR=$1
DBG_DIR=$2 
o=$3
i=$4

SCRIPT_DIR=$(dirname "$0") 
echo "Resource: " $o $i
mkdir -p $DBG_DIR/$o   
kubectl get -o=json $o $i >$DBG_DIR/$o/$i.raw.json

#skip resources that have ownerReferences as they are generated by the owner
OWNER=$(jq .metadata.ownerReferences $DBG_DIR/$o/$i.raw.json) 
if [ "$OWNER" == "null" ]; then 
    # only mkdir if outputting a file 
    mkdir -p $OUTPUT_DIR/$o   
    bash $SCRIPT_DIR/delete-unused-fields.sh $DBG_DIR/$o/$i.raw.json > $DBG_DIR/$o/$i.json
    cat $DBG_DIR/$o/$i.json | yq eval -P >  $OUTPUT_DIR/$o/$i.yaml 
else   
      KIND=$(jq ".metadata.ownerReferences[0].kind" $DBG_DIR/$o/$i.raw.json)
      NAME=$(jq ".metadata.ownerReferences[0].name" $DBG_DIR/$o/$i.raw.json)
      echo Skipping Owned Resource $o $KIND $NAME    
fi

