# Export NS 

name:  Export NS on OpenShift 
env:        
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}  
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NS}}  
on: [push, workflow_dispatch]
jobs:
  export-to-gitops:
    name: Export Namespace
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2    
      - name: Log in to OpenShift 
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - name: Run as Local Script
        run: | 
          ls -al
          export MY_EXPORT_NS=${{ env.OPENSHIFT_NAMESPACE }}
          bash ./scripts/hack.sh
      - name: Run as Local Action
        uses: ./   
        with: 
          openshift-namespace:  ${{ env.OPENSHIFT_NAMESPACE }}  

      
